package com.capstone.jrdaycare.common;

/**
 *
 * @author group2
 */
public class NotificationConstant {

    public static final String TYPE_SIGNUP = "User";
    public static final String TYPE_ADD_USER = "User";
    public static final String TYPE_ADD_NEW_PRODUCT = "Product";
    public static final String TYPE_ADD_NEW_ORDER = "Order";
    public static final String TYPE_UPDATE_ORDER_STATUS = "Order";
    public static final String TYPE_ENQUIRY = "Enquiry";
    public static final String TYPE_RMA = "RMA Request";

    public static final String TYPE_SIGNUP_CONTENT = "Is Requested For Sign Up.";
    public static final String TYPE_ADD_USER_CONTENT = "Is Added In Jr System. Please Review Once.";
    public static final String TYPE_ADD_NEW_PRODUCT_CONTENT = "One new Product Is Introduced By JR Daycare.";
    public static final String TYPE_ADD_NEW_ORDER_CONTENT = "New Order Request Genrated By";
    public static final String STATUS_CHANGE_TO_IN_PROCESS = "Your Order Is Approved And Now In Process";
    public static final String STATUS_CHANGE_TO_REJECTED = "Your Order Is Rejected By Jr ";
    public static final String STATUS_CHANGE_TO_HOLD = "Your Order Is In Hold Jr  Will Get Back To You";
    public static final String STATUS_CHANGE_TO_IN_PRODUCTION = "Your Order Is In Production Will Deliver In Short Time";
    public static final String STATUS_CHANGE_TO_IN_READY_TO_DISPATCH = "Your Order Is Ready for Dispatch";
    public static final String STATUS_CHANGE_TO_DISPATCHED = "Your Order Is Dispached";
    public static final String COMPLETE_ORDER_WHEN_RECIVED = "Please Complete Order When Goods recived By You";
    public static final String ORDER_RECEVIED_BY_USER = "Parcle Was Recived By ";
    public static final String NEW_ENQUIRY_CREATE = "New inquiry is generated By ";
    public static final String NEW_ENQUIRY_ADMIN_CHANGED_STATUS = "You Enquiry is ";
    public static final String ENQUIRY_CHANGED_STATUS = " Inquiry of ";
    public static final String NEW_RMA_REQUEST = "New RMA Request is Generated by";
    public static final String UPDATE_RMA_REQUEST = "'s RMA Request Status Changed With ";

}
