package com.capstone.jrdaycare.enquiry.repository;

import com.capstone.jrdaycare.enquiry.dto.QueryResponseDtoForPage;
import com.capstone.jrdaycare.enquiry.entity.Enquiry;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
 *
 * @author group2
 */
@Repository
public interface EnquiryRepository extends JpaRepository<Enquiry, Long> {

    @Query(value = "select * from enquiry \n"
            + "where \n"
            + "first_name ilike :firstName \n"
            + "and last_name ilike :lastName \n"
            + "and mobile_number ilike :mobileNumber \n"
            + "and house_detail ilike :houseDetail \n"
            + "and area_detail ilike :areaDetail \n"
            + "and pincode ilike :pincode ;", nativeQuery = true)
    List<Enquiry> getDuplicateEnquiry(
            @Param("firstName") String firstName,
            @Param("lastName") String lastName,
            @Param("mobileNumber") String mobileNumber,
            @Param("houseDetail") String houseDetail,
            @Param("areaDetail") String areaDetail,
            @Param("pincode") String pincode
    );

    @Query(value = "select \n"
            + "eq.inquiry_id as \"enquiryId\", \n"
            + "eq.first_name as \"firstName\",\n"
            + "eq.last_name as \"lastName\",\n"
            + "eq.mobile_number as \"mobileNumber\",\n"
            + "eq.second_number as \"secondNumber\",\n"
            + "eq.house_detail as \"houseDetail\",\n"
            + "eq.area_detail as \"areaDetail\",\n"
            + "eq.pincode as \"pincode\",\n"
            + "eq.interior_name as \"interiorName\",\n"
            + "eq.description as \"description\",\n"
            + "eq.inquiry_type as \"inquiryType\",\n"
            + "eq.status as \"status\",\n"
            + "eq.created_on as \"createdOn\",\n"
            + "eq.owner as \"owner\",\n"
            + "eq.owner_name as \"ownerName\",\n"
            + "us.business_name as \"businessName\",\n"
            + "eq.city_id as \"cityId\",\n"
            + "eq.district_id as \"districtId\",\n"
            + "eq.state_id as \"stateId\",\n"
            + "cl.city_title as \"cityTitle\",\n"
            + "dl.district_title as \"districtTitle\",\n"
            + "sl.state_title as \"stateTitle\"\n"
            + "from enquiry as eq\n"
            + "left join users as us on eq.created_by = us.id \n"
            + "left join city_location as cl on eq.city_id = cl.city_id\n"
            + "left join district_location as dl on eq.district_id = dl.district_id\n"
            + "left join state_location as sl on eq.state_id = sl.state_id\n"
            + "where eq.status != 'PENDING' and eq.status != 'REJECTED_BY_JR' and eq.status != 'CANCEL_BY_CLIENT' and eq.status != 'COMPLETED' \n"
            + "order by eq.created_on desc\n"
            + "offset :offset\n"
            + "limit :limit ;", nativeQuery = true)
    List<QueryResponseDtoForPage> getAllEnquiryPageWithoutSearch(
            @Param("offset") Integer offset,
            @Param("limit") Integer limit);

    @Query(value = "select count(*) \n"
            + "from enquiry as eq\n"
            + "left join users as us on eq.created_by = us.id \n"
            + "left join city_location as cl on eq.city_id = cl.city_id\n"
            + "left join district_location as dl on eq.district_id = dl.district_id\n"
            + "left join state_location as sl on eq.state_id = sl.state_id\n"
            + "where eq.status != 'PENDING' and eq.status != 'REJECTED_BY_JR' and eq.status != 'CANCEL_BY_CLIENT' and eq.status != 'COMPLETED';", nativeQuery = true)
    Long getAllEnquiryPageWithoutSearchCount();

    @Query(value = "select \n"
            + "eq.inquiry_id as \"enquiryId\", \n"
            + "eq.first_name as \"firstName\",\n"
            + "eq.last_name as \"lastName\",\n"
            + "eq.mobile_number as \"mobileNumber\",\n"
            + "eq.second_number as \"secondNumber\",\n"
            + "eq.house_detail as \"houseDetail\",\n"
            + "eq.area_detail as \"areaDetail\",\n"
            + "eq.pincode as \"pincode\",\n"
            + "eq.interior_name as \"interiorName\",\n"
            + "eq.description as \"description\",\n"
            + "eq.status as \"status\",\n"
            + "eq.inquiry_type as \"inquiryType\",\n"
            + "eq.created_on as \"createdOn\",\n"
            + "eq.owner as \"owner\",\n"
            + "eq.owner_name as \"ownerName\",\n"
            + "us.business_name as \"businessName\",\n"
            + "eq.city_id as \"cityId\",\n"
            + "eq.district_id as \"districtId\",\n"
            + "eq.state_id as \"stateId\",\n"
            + "cl.city_title as \"cityTitle\",\n"
            + "dl.district_title as \"districtTitle\",\n"
            + "sl.state_title as \"stateTitle\"\n"
            + "from enquiry as eq\n"
            + "left join users as us on eq.created_by = us.id \n"
            + "left join city_location as cl on eq.city_id = cl.city_id\n"
            + "left join district_location as dl on eq.district_id = dl.district_id\n"
            + "left join state_location as sl on eq.state_id = sl.state_id\n"
            + "where (eq.status != 'REJECTED_BY_JR' and eq.status != 'CANCEL_BY_CLIENT' and eq.status != 'COMPLETED') and eq.created_by in :child \n"
            + "order by eq.created_on desc\n"
            + "offset :offset\n"
            + "limit :limit ;", nativeQuery = true)
    List<QueryResponseDtoForPage> getAllEnquiryPageWithoutSearchForDl(
            @Param("offset") Integer offset,
            @Param("limit") Integer limit,
            @Param("child") List<Long> child);

    @Query(value = "select count(*) \n"
            + "from enquiry as eq\n"
            + "left join users as us on eq.created_by = us.id \n"
            + "left join city_location as cl on eq.city_id = cl.city_id\n"
            + "left join district_location as dl on eq.district_id = dl.district_id\n"
            + "left join state_location as sl on eq.state_id = sl.state_id\n"
            + "where (eq.status != 'REJECTED_BY_JR' and eq.status != 'CANCEL_BY_CLIENT' and eq.status != 'COMPLETED') and eq.created_by in :child ;", nativeQuery = true)
    Long getAllEnquiryPageWithoutSearchCountForDl(@Param("child") List<Long> child);

    @Query(value = "select \n"
            + "eq.inquiry_id as \"enquiryId\", \n"
            + "eq.first_name as \"firstName\",\n"
            + "eq.last_name as \"lastName\",\n"
            + "eq.mobile_number as \"mobileNumber\",\n"
            + "eq.second_number as \"secondNumber\",\n"
            + "eq.house_detail as \"houseDetail\",\n"
            + "eq.area_detail as \"areaDetail\",\n"
            + "eq.pincode as \"pincode\",\n"
            + "eq.interior_name as \"interiorName\",\n"
            + "eq.description as \"description\",\n"
            + "eq.status as \"status\",\n"
            + "eq.created_on as \"createdOn\",\n"
            + "us.business_name as \"businessName\",\n"
            + "eq.owner as \"owner\",\n"
            + "eq.owner_name as \"ownerName\",\n"
            + "eq.city_id as \"cityId\",\n"
            + "eq.district_id as \"districtId\",\n"
            + "eq.state_id as \"stateId\",\n"
            + "eq.inquiry_type as \"inquiryType\",\n"
            + "cl.city_title as \"cityTitle\",\n"
            + "dl.district_title as \"districtTitle\",\n"
            + "sl.state_title as \"stateTitle\"\n"
            + "from enquiry as eq\n"
            + "left join users as us on eq.created_by = us.id \n"
            + "left join city_location as cl on eq.city_id = cl.city_id\n"
            + "left join district_location as dl on eq.district_id = dl.district_id\n"
            + "left join state_location as sl on eq.state_id = sl.state_id\n"
            + "where (eq.status != 'PENDING' and eq.status != 'REJECTED_BY_JR' and eq.status != 'CANCEL_BY_CLIENT' and eq.status != 'COMPLETED') and \n"
            + "(\n"
            + "eq.first_name ilike %:search% or\n"
            + "eq.last_name ilike %:search% or\n"
            + "eq.mobile_number ilike %:search% or\n"
            + "eq.status ilike %:search% or\n"
            + "eq.second_number ilike %:search% or\n"
            + "eq.house_detail ilike %:search% or\n"
            + "eq.area_detail ilike %:search% or\n"
            + "eq.pincode ilike %:search% or\n"
            + "eq.inquiry_type ilike %:search% or\n"
            + "eq.interior_name ilike %:search% or\n"
            + "eq.owner_name ilike %:search% or\n"
            + "eq.description ilike %:search% or\n"
            + "eq.status ilike %:search% or\n"
            + "us.business_name ilike %:search% or\n"
            + "cl.city_title ilike %:search% or\n"
            + "dl.district_title ilike %:search% or\n"
            + "sl.state_title ilike %:search%\n"
            + " )\n"
            + "order by eq.created_on desc\n"
            + "offset :offset \n"
            + "limit :limit ;", nativeQuery = true)
    List<QueryResponseDtoForPage> getAllEnquiryPageWith(
            @Param("offset") Integer offset,
            @Param("limit") Integer limit,
            @Param("search") String search);

    @Query(value = "select count(*) \n"
            + "from enquiry as eq\n"
            + "left join users as us on eq.created_by = us.id \n"
            + "left join city_location as cl on eq.city_id = cl.city_id\n"
            + "left join district_location as dl on eq.district_id = dl.district_id\n"
            + "left join state_location as sl on eq.state_id = sl.state_id\n"
            + "where (eq.status != 'PENDING' and eq.status != 'REJECTED_BY_JR' and eq.status != 'CANCEL_BY_CLIENT' and eq.status != 'COMPLETED') and \n"
            + "(\n"
            + "eq.first_name ilike %:search% or\n"
            + "eq.last_name ilike %:search% or\n"
            + "eq.status ilike %:search% or\n"
            + "eq.mobile_number ilike %:search% or\n"
            + "eq.owner_name ilike %:search% or\n"
            + "eq.second_number ilike %:search% or\n"
            + "eq.house_detail ilike %:search% or\n"
            + "eq.area_detail ilike %:search% or\n"
            + "eq.inquiry_type ilike %:search% or\n"
            + "eq.owner_name ilike %:search% or\n"
            + "eq.pincode ilike %:search% or\n"
            + "eq.interior_name ilike %:search% or\n"
            + "eq.description ilike %:search% or\n"
            + "eq.status ilike %:search% or\n"
            + "us.business_name ilike %:search% or\n"
            + "cl.city_title ilike %:search% or\n"
            + "dl.district_title ilike %:search% or\n"
            + "sl.state_title ilike %:search%\n"
            + " )\n", nativeQuery = true)
    Long getAllEnquiryPageWithCount(
            @Param("search") String search);

    @Query(value = "select \n"
            + "eq.inquiry_id as \"enquiryId\", \n"
            + "eq.first_name as \"firstName\",\n"
            + "eq.last_name as \"lastName\",\n"
            + "eq.mobile_number as \"mobileNumber\",\n"
            + "eq.second_number as \"secondNumber\",\n"
            + "eq.house_detail as \"houseDetail\",\n"
            + "eq.area_detail as \"areaDetail\",\n"
            + "eq.pincode as \"pincode\",\n"
            + "eq.interior_name as \"interiorName\",\n"
            + "eq.owner as \"owner\",\n"
            + "eq.owner_name as \"ownerName\",\n"
            + "eq.description as \"description\",\n"
            + "eq.status as \"status\",\n"
            + "eq.created_on as \"createdOn\",\n"
            + "us.business_name as \"businessName\",\n"
            + "eq.city_id as \"cityId\",\n"
            + "eq.inquiry_type as \"inquiryType\",\n"
            + "eq.district_id as \"districtId\",\n"
            + "eq.state_id as \"stateId\",\n"
            + "cl.city_title as \"cityTitle\",\n"
            + "dl.district_title as \"districtTitle\",\n"
            + "sl.state_title as \"stateTitle\"\n"
            + "from enquiry as eq\n"
            + "left join users as us on eq.created_by = us.id \n"
            + "left join city_location as cl on eq.city_id = cl.city_id\n"
            + "left join district_location as dl on eq.district_id = dl.district_id\n"
            + "left join state_location as sl on eq.state_id = sl.state_id\n"
            + "where (eq.status != 'REJECTED_BY_JR' and eq.status != 'CANCEL_BY_CLIENT' and eq.status != 'COMPLETED') and eq.created_by in :child and \n"
            + "(\n"
            + "eq.first_name ilike %:search% or\n"
            + "eq.last_name ilike %:search% or\n"
            + "eq.status ilike %:search% or\n"
            + "eq.mobile_number ilike %:search% or\n"
            + "eq.second_number ilike %:search% or\n"
            + "eq.house_detail ilike %:search% or\n"
            + "eq.area_detail ilike %:search% or\n"
            + "eq.owner_name ilike %:search% or\n"
            + "eq.inquiry_type ilike %:search% or\n"
            + "eq.pincode ilike %:search% or\n"
            + "eq.interior_name ilike %:search% or\n"
            + "eq.description ilike %:search% or\n"
            + "eq.status ilike %:search% or\n"
            + "us.business_name ilike %:search% or\n"
            + "cl.city_title ilike %:search% or\n"
            + "dl.district_title ilike %:search% or\n"
            + "sl.state_title ilike %:search%\n"
            + " )\n"
            + "order by eq.created_on desc\n"
            + "offset :offset \n"
            + "limit :limit ;", nativeQuery = true)
    List<QueryResponseDtoForPage> getAllEnquiryPageWithForDl(
            @Param("offset") Integer offset,
            @Param("limit") Integer limit,
            @Param("search") String search,
            @Param("child") List<Long> child);

    @Query(value = "select count(*) \n"
            + "from enquiry as eq\n"
            + "left join users as us on eq.created_by = us.id \n"
            + "left join city_location as cl on eq.city_id = cl.city_id\n"
            + "left join district_location as dl on eq.district_id = dl.district_id\n"
            + "left join state_location as sl on eq.state_id = sl.state_id\n"
            + "where (eq.status != 'REJECTED_BY_JR' and eq.status != 'CANCEL_BY_CLIENT' and eq.status != 'COMPLETED') and eq.created_by in :child  and \n"
            + "(\n"
            + "eq.first_name ilike %:search% or\n"
            + "eq.status ilike %:search% or\n"
            + "eq.last_name ilike %:search% or\n"
            + "eq.mobile_number ilike %:search% or\n"
            + "eq.second_number ilike %:search% or\n"
            + "eq.house_detail ilike %:search% or\n"
            + "eq.area_detail ilike %:search% or\n"
            + "eq.inquiry_type ilike %:search% or\n"
            + "eq.pincode ilike %:search% or\n"
            + "eq.owner_name ilike %:search% or\n"
            + "eq.interior_name ilike %:search% or\n"
            + "eq.description ilike %:search% or\n"
            + "eq.status ilike %:search% or\n"
            + "us.business_name ilike %:search% or\n"
            + "cl.city_title ilike %:search% or\n"
            + "dl.district_title ilike %:search% or\n"
            + "sl.state_title ilike %:search%\n"
            + " )\n ;", nativeQuery = true)
    Long getAllEnquiryPageWithCountForDl(
            @Param("search") String search,
            @Param("child") List<Long> child);

    @Query(value = "select \n"
            + "eq.inquiry_id as \"enquiryId\", \n"
            + "eq.first_name as \"firstName\",\n"
            + "eq.last_name as \"lastName\",\n"
            + "eq.mobile_number as \"mobileNumber\",\n"
            + "eq.second_number as \"secondNumber\",\n"
            + "eq.house_detail as \"houseDetail\",\n"
            + "eq.area_detail as \"areaDetail\",\n"
            + "eq.pincode as \"pincode\",\n"
            + "eq.interior_name as \"interiorName\",\n"
            + "eq.description as \"description\",\n"
            + "eq.status as \"status\",\n"
            + "eq.created_on as \"createdOn\",\n"
            + "eq.inquiry_type as \"inquiryType\",\n"
            + "eq.owner as \"owner\",\n"
            + "eq.owner_name as \"ownerName\",\n"
            + "us.business_name as \"businessName\",\n"
            + "eq.city_id as \"cityId\",\n"
            + "eq.district_id as \"districtId\",\n"
            + "eq.state_id as \"stateId\",\n"
            + "cl.city_title as \"cityTitle\",\n"
            + "dl.district_title as \"districtTitle\",\n"
            + "sl.state_title as \"stateTitle\"\n"
            + "from enquiry as eq\n"
            + "left join users as us on eq.created_by = us.id \n"
            + "left join city_location as cl on eq.city_id = cl.city_id\n"
            + "left join district_location as dl on eq.district_id = dl.district_id\n"
            + "left join state_location as sl on eq.state_id = sl.state_id\n"
            + "where eq.status = 'PENDING' and \n"
            + "(\n"
            + "eq.first_name ilike %:search% or\n"
            + "eq.last_name ilike %:search% or\n"
            + "eq.status ilike %:search% or\n"
            + "eq.mobile_number ilike %:search% or\n"
            + "eq.second_number ilike %:search% or\n"
            + "eq.house_detail ilike %:search% or\n"
            + "eq.area_detail ilike %:search% or\n"
            + "eq.inquiry_type ilike %:search% or\n"
            + "eq.owner_name ilike %:search% or\n"
            + "eq.pincode ilike %:search% or\n"
            + "eq.interior_name ilike %:search% or\n"
            + "eq.description ilike %:search% or\n"
            + "eq.status ilike %:search% or\n"
            + "us.business_name ilike %:search% or\n"
            + "cl.city_title ilike %:search% or\n"
            + "dl.district_title ilike %:search% or\n"
            + "sl.state_title ilike %:search%\n"
            + " )\n"
            + "order by eq.created_on desc\n"
            + "offset :offset \n"
            + "limit :limit ;", nativeQuery = true)
    List<QueryResponseDtoForPage> getPendinfEnquiryPageWithSearch(
            @Param("offset") Integer offset,
            @Param("limit") Integer limit,
            @Param("search") String search);

    @Query(value = "select count(*) \n"
            + "from enquiry as eq\n"
            + "left join users as us on eq.created_by = us.id \n"
            + "left join city_location as cl on eq.city_id = cl.city_id\n"
            + "left join district_location as dl on eq.district_id = dl.district_id\n"
            + "left join state_location as sl on eq.state_id = sl.state_id\n"
            + "where eq.status = 'PENDING' and \n"
            + "(\n"
            + "eq.first_name ilike %:search% or\n"
            + "eq.last_name ilike %:search% or\n"
            + "eq.status ilike %:search% or\n"
            + "eq.mobile_number ilike %:search% or\n"
            + "eq.second_number ilike %:search% or\n"
            + "eq.house_detail ilike %:search% or\n"
            + "eq.area_detail ilike %:search% or\n"
            + "eq.inquiry_type ilike %:search% or\n"
            + "eq.owner_name ilike %:search% or\n"
            + "eq.pincode ilike %:search% or\n"
            + "eq.interior_name ilike %:search% or\n"
            + "eq.description ilike %:search% or\n"
            + "eq.status ilike %:search% or\n"
            + "us.business_name ilike %:search% or\n"
            + "cl.city_title ilike %:search% or\n"
            + "dl.district_title ilike %:search% or\n"
            + "sl.state_title ilike %:search% );", nativeQuery = true)
    Long getPendingEnquiryPageWithSearchCount(
            @Param("search") String search);

    @Query(value = "select \n"
            + "eq.inquiry_id as \"enquiryId\", \n"
            + "eq.first_name as \"firstName\",\n"
            + "eq.last_name as \"lastName\",\n"
            + "eq.mobile_number as \"mobileNumber\",\n"
            + "eq.second_number as \"secondNumber\",\n"
            + "eq.house_detail as \"houseDetail\",\n"
            + "eq.area_detail as \"areaDetail\",\n"
            + "eq.pincode as \"pincode\",\n"
            + "eq.interior_name as \"interiorName\",\n"
            + "eq.description as \"description\",\n"
            + "eq.status as \"status\",\n"
            + "eq.inquiry_type as \"inquiryType\",\n"
            + "eq.created_on as \"createdOn\",\n"
            + "eq.owner as \"owner\",\n"
            + "eq.owner_name as \"ownerName\",\n"
            + "us.business_name as \"businessName\",\n"
            + "eq.city_id as \"cityId\",\n"
            + "eq.district_id as \"districtId\",\n"
            + "eq.state_id as \"stateId\",\n"
            + "cl.city_title as \"cityTitle\",\n"
            + "dl.district_title as \"districtTitle\",\n"
            + "sl.state_title as \"stateTitle\"\n"
            + "from enquiry as eq\n"
            + "left join users as us on eq.created_by = us.id \n"
            + "left join city_location as cl on eq.city_id = cl.city_id\n"
            + "left join district_location as dl on eq.district_id = dl.district_id\n"
            + "left join state_location as sl on eq.state_id = sl.state_id\n"
            + "where eq.status = 'PENDING'\n"
            + "order by eq.created_on desc\n"
            + "offset :offset\n"
            + "limit :limit ;", nativeQuery = true)
    List<QueryResponseDtoForPage> getPendingEnquiryPageWithoutSearch(
            @Param("offset") Integer offset,
            @Param("limit") Integer limit);

    @Query(value = "select count(*) \n"
            + "from enquiry as eq\n"
            + "left join users as us on eq.created_by = us.id \n"
            + "left join city_location as cl on eq.city_id = cl.city_id\n"
            + "left join district_location as dl on eq.district_id = dl.district_id\n"
            + "left join state_location as sl on eq.state_id = sl.state_id\n"
            + "where eq.status = 'PENDING' ;", nativeQuery = true)
    Long getPendingEnquiryPageWithoutSearchCount();

    @Query(value = "select \n"
            + "eq.inquiry_id as \"enquiryId\", \n"
            + "eq.first_name as \"firstName\",\n"
            + "eq.last_name as \"lastName\",\n"
            + "eq.mobile_number as \"mobileNumber\",\n"
            + "eq.second_number as \"secondNumber\",\n"
            + "eq.house_detail as \"houseDetail\",\n"
            + "eq.area_detail as \"areaDetail\",\n"
            + "eq.pincode as \"pincode\",\n"
            + "eq.interior_name as \"interiorName\",\n"
            + "eq.description as \"description\",\n"
            + "eq.status as \"status\",\n"
            + "eq.inquiry_type as \"inquiryType\",\n"
            + "eq.created_on as \"createdOn\",\n"
            + "us.business_name as \"businessName\",\n"
            + "eq.owner as \"owner\",\n"
            + "eq.owner_name as \"ownerName\",\n"
            + "eq.city_id as \"cityId\",\n"
            + "eq.district_id as \"districtId\",\n"
            + "eq.state_id as \"stateId\",\n"
            + "cl.city_title as \"cityTitle\",\n"
            + "dl.district_title as \"districtTitle\",\n"
            + "sl.state_title as \"stateTitle\"\n"
            + "from enquiry as eq\n"
            + "left join users as us on eq.created_by = us.id \n"
            + "left join city_location as cl on eq.city_id = cl.city_id\n"
            + "left join district_location as dl on eq.district_id = dl.district_id\n"
            + "left join state_location as sl on eq.state_id = sl.state_id\n"
            + "where (eq.status = 'REJECTED_BY_JR' or eq.status = 'CANCEL_BY_CLIENT' or eq.status = 'COMPLETED') and \n"
            + "(\n"
            + "eq.first_name ilike %:search% or\n"
            + "eq.last_name ilike %:search% or\n"
            + "eq.mobile_number ilike %:search% or\n"
            + "eq.status ilike %:search% or\n"
            + "eq.second_number ilike %:search% or\n"
            + "eq.house_detail ilike %:search% or\n"
            + "eq.area_detail ilike %:search% or\n"
            + "eq.pincode ilike %:search% or\n"
            + "eq.inquiry_type ilike %:search% or\n"
            + "eq.interior_name ilike %:search% or\n"
            + "eq.owner_name ilike %:search% or\n"
            + "eq.description ilike %:search% or\n"
            + "eq.status ilike %:search% or\n"
            + "us.business_name ilike %:search% or\n"
            + "cl.city_title ilike %:search% or\n"
            + "dl.district_title ilike %:search% or\n"
            + "sl.state_title ilike %:search%\n"
            + " )\n"
            + "order by eq.created_on desc\n"
            + "offset :offset \n"
            + "limit :limit ;", nativeQuery = true)
    List<QueryResponseDtoForPage> getAllFinishedEnquiryPageWith(
            @Param("offset") Integer offset,
            @Param("limit") Integer limit,
            @Param("search") String search);

    @Query(value = "select count(*) \n"
            + "from enquiry as eq\n"
            + "left join users as us on eq.created_by = us.id \n"
            + "left join city_location as cl on eq.city_id = cl.city_id\n"
            + "left join district_location as dl on eq.district_id = dl.district_id\n"
            + "left join state_location as sl on eq.state_id = sl.state_id\n"
            + "where (eq.status = 'REJECTED_BY_JR' or eq.status = 'CANCEL_BY_CLIENT' or eq.status = 'COMPLETED') and \n"
            + "(\n"
            + "eq.first_name ilike %:search% or\n"
            + "eq.last_name ilike %:search% or\n"
            + "eq.status ilike %:search% or\n"
            + "eq.mobile_number ilike %:search% or\n"
            + "eq.owner_name ilike %:search% or\n"
            + "eq.second_number ilike %:search% or\n"
            + "eq.house_detail ilike %:search% or\n"
            + "eq.area_detail ilike %:search% or\n"
            + "eq.inquiry_type ilike %:search% or\n"
            + "eq.owner_name ilike %:search% or\n"
            + "eq.pincode ilike %:search% or\n"
            + "eq.interior_name ilike %:search% or\n"
            + "eq.description ilike %:search% or\n"
            + "eq.status ilike %:search% or\n"
            + "us.business_name ilike %:search% or\n"
            + "cl.city_title ilike %:search% or\n"
            + "dl.district_title ilike %:search% or\n"
            + "sl.state_title ilike %:search%\n"
            + " );", nativeQuery = true)
    Long getAllFinishedEnquiryPageWithCount(
            @Param("search") String search);

    @Query(value = "select \n"
            + "eq.inquiry_id as \"enquiryId\", \n"
            + "eq.first_name as \"firstName\",\n"
            + "eq.last_name as \"lastName\",\n"
            + "eq.mobile_number as \"mobileNumber\",\n"
            + "eq.second_number as \"secondNumber\",\n"
            + "eq.house_detail as \"houseDetail\",\n"
            + "eq.area_detail as \"areaDetail\",\n"
            + "eq.inquiry_type as \"inquiryType\",\n"
            + "eq.pincode as \"pincode\",\n"
            + "eq.interior_name as \"interiorName\",\n"
            + "eq.description as \"description\",\n"
            + "eq.status as \"status\",\n"
            + "eq.created_on as \"createdOn\",\n"
            + "eq.owner as \"owner\",\n"
            + "eq.owner_name as \"ownerName\",\n"
            + "us.business_name as \"businessName\",\n"
            + "eq.city_id as \"cityId\",\n"
            + "eq.district_id as \"districtId\",\n"
            + "eq.state_id as \"stateId\",\n"
            + "cl.city_title as \"cityTitle\",\n"
            + "dl.district_title as \"districtTitle\",\n"
            + "sl.state_title as \"stateTitle\"\n"
            + "from enquiry as eq\n"
            + "left join users as us on eq.created_by = us.id \n"
            + "left join city_location as cl on eq.city_id = cl.city_id\n"
            + "left join district_location as dl on eq.district_id = dl.district_id\n"
            + "left join state_location as sl on eq.state_id = sl.state_id\n"
            + "where eq.status = 'REJECTED_BY_JR' or eq.status = 'CANCEL_BY_CLIENT' or eq.status = 'COMPLETED' \n"
            + "order by eq.created_on desc\n"
            + "offset :offset\n"
            + "limit :limit ;", nativeQuery = true)
    List<QueryResponseDtoForPage> getFinishedEnquiryPageWithoutSearch(
            @Param("offset") Integer offset,
            @Param("limit") Integer limit);

    @Query(value = "select count(*) \n"
            + "from enquiry as eq\n"
            + "left join users as us on eq.created_by = us.id \n"
            + "left join city_location as cl on eq.city_id = cl.city_id\n"
            + "left join district_location as dl on eq.district_id = dl.district_id\n"
            + "left join state_location as sl on eq.state_id = sl.state_id\n"
            + "where eq.status = 'REJECTED_BY_JR' or eq.status = 'CANCEL_BY_CLIENT' or eq.status = 'COMPLETED';", nativeQuery = true)
    Long getFinishedEnquiryPageWithoutSearchCount();

    @Query(value = "select \n"
            + "eq.inquiry_id as \"enquiryId\", \n"
            + "eq.first_name as \"firstName\",\n"
            + "eq.last_name as \"lastName\",\n"
            + "eq.mobile_number as \"mobileNumber\",\n"
            + "eq.second_number as \"secondNumber\",\n"
            + "eq.house_detail as \"houseDetail\",\n"
            + "eq.area_detail as \"areaDetail\",\n"
            + "eq.pincode as \"pincode\",\n"
            + "eq.interior_name as \"interiorName\",\n"
            + "eq.owner as \"owner\",\n"
            + "eq.owner_name as \"ownerName\",\n"
            + "eq.description as \"description\",\n"
            + "eq.status as \"status\",\n"
            + "eq.inquiry_type as \"inquiryType\",\n"
            + "eq.created_on as \"createdOn\",\n"
            + "us.business_name as \"businessName\",\n"
            + "eq.city_id as \"cityId\",\n"
            + "eq.district_id as \"districtId\",\n"
            + "eq.state_id as \"stateId\",\n"
            + "cl.city_title as \"cityTitle\",\n"
            + "dl.district_title as \"districtTitle\",\n"
            + "sl.state_title as \"stateTitle\"\n"
            + "from enquiry as eq\n"
            + "left join users as us on eq.created_by = us.id \n"
            + "left join city_location as cl on eq.city_id = cl.city_id\n"
            + "left join district_location as dl on eq.district_id = dl.district_id\n"
            + "left join state_location as sl on eq.state_id = sl.state_id\n"
            + "where (eq.status = 'REJECTED_BY_JR' or eq.status = 'CANCEL_BY_CLIENT' or eq.status = 'COMPLETED') and eq.created_by in :child and \n"
            + "(\n"
            + "eq.first_name ilike %:search% or\n"
            + "eq.last_name ilike %:search% or\n"
            + "eq.status ilike %:search% or\n"
            + "eq.mobile_number ilike %:search% or\n"
            + "eq.second_number ilike %:search% or\n"
            + "eq.house_detail ilike %:search% or\n"
            + "eq.area_detail ilike %:search% or\n"
            + "eq.owner_name ilike %:search% or\n"
            + "eq.pincode ilike %:search% or\n"
            + "eq.inquiry_type ilike %:search% or\n"
            + "eq.interior_name ilike %:search% or\n"
            + "eq.description ilike %:search% or\n"
            + "eq.status ilike %:search% or\n"
            + "us.business_name ilike %:search% or\n"
            + "cl.city_title ilike %:search% or\n"
            + "dl.district_title ilike %:search% or\n"
            + "sl.state_title ilike %:search%\n"
            + " )\n"
            + "order by eq.created_on desc\n"
            + "offset :offset \n"
            + "limit :limit ;", nativeQuery = true)
    List<QueryResponseDtoForPage> getFinishedEnquiryPageWithForDl(
            @Param("offset") Integer offset,
            @Param("limit") Integer limit,
            @Param("search") String search,
            @Param("child") List<Long> child);

    @Query(value = "select count(*) \n"
            + "from enquiry as eq\n"
            + "left join users as us on eq.created_by = us.id \n"
            + "left join city_location as cl on eq.city_id = cl.city_id\n"
            + "left join district_location as dl on eq.district_id = dl.district_id\n"
            + "left join state_location as sl on eq.state_id = sl.state_id\n"
            + "where (eq.status = 'REJECTED_BY_JR' or eq.status = 'CANCEL_BY_CLIENT' or eq.status = 'COMPLETED') and eq.created_by in :child  and \n"
            + "(\n"
            + "eq.first_name ilike %:search% or\n"
            + "eq.status ilike %:search% or\n"
            + "eq.last_name ilike %:search% or\n"
            + "eq.mobile_number ilike %:search% or\n"
            + "eq.second_number ilike %:search% or\n"
            + "eq.house_detail ilike %:search% or\n"
            + "eq.area_detail ilike %:search% or\n"
            + "eq.pincode ilike %:search% or\n"
            + "eq.inquiry_type ilike %:search% or\n"
            + "eq.owner_name ilike %:search% or\n"
            + "eq.interior_name ilike %:search% or\n"
            + "eq.description ilike %:search% or\n"
            + "eq.status ilike %:search% or\n"
            + "us.business_name ilike %:search% or\n"
            + "cl.city_title ilike %:search% or\n"
            + "dl.district_title ilike %:search% or\n"
            + "sl.state_title ilike %:search%\n"
            + " );", nativeQuery = true)
    Long getFinishedEnquiryPageWithCountForDl(
            @Param("search") String search,
            @Param("child") List<Long> child);

    @Query(value = "select \n"
            + "eq.inquiry_id as \"enquiryId\", \n"
            + "eq.first_name as \"firstName\",\n"
            + "eq.last_name as \"lastName\",\n"
            + "eq.mobile_number as \"mobileNumber\",\n"
            + "eq.second_number as \"secondNumber\",\n"
            + "eq.house_detail as \"houseDetail\",\n"
            + "eq.area_detail as \"areaDetail\",\n"
            + "eq.pincode as \"pincode\",\n"
            + "eq.interior_name as \"interiorName\",\n"
            + "eq.description as \"description\",\n"
            + "eq.status as \"status\",\n"
            + "eq.inquiry_type as \"inquiryType\",\n"
            + "eq.created_on as \"createdOn\",\n"
            + "eq.owner as \"owner\",\n"
            + "eq.owner_name as \"ownerName\",\n"
            + "us.business_name as \"businessName\",\n"
            + "eq.city_id as \"cityId\",\n"
            + "eq.district_id as \"districtId\",\n"
            + "eq.state_id as \"stateId\",\n"
            + "cl.city_title as \"cityTitle\",\n"
            + "dl.district_title as \"districtTitle\",\n"
            + "sl.state_title as \"stateTitle\"\n"
            + "from enquiry as eq\n"
            + "left join users as us on eq.created_by = us.id \n"
            + "left join city_location as cl on eq.city_id = cl.city_id\n"
            + "left join district_location as dl on eq.district_id = dl.district_id\n"
            + "left join state_location as sl on eq.state_id = sl.state_id\n"
            + "where (eq.status = 'REJECTED_BY_JR' or eq.status = 'CANCEL_BY_CLIENT' or eq.status = 'COMPLETED') and eq.created_by in :child \n"
            + "order by eq.created_on desc\n"
            + "offset :offset\n"
            + "limit :limit ;", nativeQuery = true)
    List<QueryResponseDtoForPage> getFinishedEnquiryPageWithoutSearchForDl(
            @Param("offset") Integer offset,
            @Param("limit") Integer limit,
            @Param("child") List<Long> child);

    @Query(value = "select count(*) \n"
            + "from enquiry as eq\n"
            + "left join users as us on eq.created_by = us.id \n"
            + "left join city_location as cl on eq.city_id = cl.city_id\n"
            + "left join district_location as dl on eq.district_id = dl.district_id\n"
            + "left join state_location as sl on eq.state_id = sl.state_id\n"
            + "where (eq.status = 'REJECTED_BY_JR' or eq.status = 'CANCEL_BY_CLIENT' or eq.status = 'COMPLETED') and eq.created_by in :child ;", nativeQuery = true)
    Long getFinishedEnquiryPageWithoutSearchCountForDl(@Param("child") List<Long> child);

    @Query(value = "select \n"
            + "eq.inquiry_id as \"enquiryId\", \n"
            + "eq.first_name as \"firstName\",\n"
            + "eq.last_name as \"lastName\",\n"
            + "eq.mobile_number as \"mobileNumber\",\n"
            + "eq.second_number as \"secondNumber\",\n"
            + "eq.house_detail as \"houseDetail\",\n"
            + "eq.area_detail as \"areaDetail\",\n"
            + "eq.pincode as \"pincode\",\n"
            + "eq.interior_name as \"interiorName\",\n"
            + "eq.description as \"description\",\n"
            + "eq.status as \"status\",\n"
            + "eq.created_on as \"createdOn\",\n"
            + "us.business_name as \"businessName\",\n"
            + "eq.owner as \"owner\",\n"
            + "eq.owner_name as \"ownerName\",\n"
            + "eq.city_id as \"cityId\",\n"
            + "eq.district_id as \"districtId\",\n"
            + "eq.state_id as \"stateId\",\n"
            + "eq.inquiry_type as \"inquiryType\",\n"
            + "cl.city_title as \"cityTitle\",\n"
            + "dl.district_title as \"districtTitle\",\n"
            + "sl.state_title as \"stateTitle\"\n"
            + "from enquiry as eq\n"
            + "left join users as us on eq.created_by = us.id \n"
            + "left join city_location as cl on eq.city_id = cl.city_id\n"
            + "left join district_location as dl on eq.district_id = dl.district_id\n"
            + "left join state_location as sl on eq.state_id = sl.state_id\n"
            + "order by eq.created_on desc\n"
            + "offset :offset \n"
            + "limit :limit ;", nativeQuery = true)
    List<QueryResponseDtoForPage> getLatestTen(
            @Param("offset") Integer offset,
            @Param("limit") Integer limit);

    @Query(value = "select \n"
            + "eq.inquiry_id as \"enquiryId\", \n"
            + "eq.first_name as \"firstName\",\n"
            + "eq.last_name as \"lastName\",\n"
            + "eq.mobile_number as \"mobileNumber\",\n"
            + "eq.second_number as \"secondNumber\",\n"
            + "eq.house_detail as \"houseDetail\",\n"
            + "eq.area_detail as \"areaDetail\",\n"
            + "eq.pincode as \"pincode\",\n"
            + "eq.interior_name as \"interiorName\",\n"
            + "eq.description as \"description\",\n"
            + "eq.status as \"status\",\n"
            + "eq.created_on as \"createdOn\",\n"
            + "us.business_name as \"businessName\",\n"
            + "eq.owner as \"owner\",\n"
            + "eq.owner_name as \"ownerName\",\n"
            + "eq.city_id as \"cityId\",\n"
            + "eq.district_id as \"districtId\",\n"
            + "eq.state_id as \"stateId\",\n"
            + "eq.inquiry_type as \"inquiryType\",\n"
            + "cl.city_title as \"cityTitle\",\n"
            + "dl.district_title as \"districtTitle\",\n"
            + "sl.state_title as \"stateTitle\"\n"
            + "from enquiry as eq\n"
            + "left join users as us on eq.created_by = us.id \n"
            + "left join city_location as cl on eq.city_id = cl.city_id\n"
            + "left join district_location as dl on eq.district_id = dl.district_id\n"
            + "left join state_location as sl on eq.state_id = sl.state_id where eq.owner = :owner \n"
            + "order by eq.created_on desc\n"
            + "offset :offset \n"
            + "limit :limit ;", nativeQuery = true)
    List<QueryResponseDtoForPage> getLatestTenForPartner(
            @Param("offset") Integer offset,
            @Param("owner") Long owner,
            @Param("limit") Integer limit);

    @Query(value = "SELECT COUNT(*)\n"
            + "FROM ENQUIRY\n"
            + "WHERE DATE_PART('month', (CREATED_ON)) = DATE_PART('month', (NOW())) -1\n"
            + "	AND DATE_PART('year', (CREATED_ON)) = DATE_PART('year', (NOW()))", nativeQuery = true)
    Long lastMonthEnquiry();

    @Query(value = "SELECT COUNT(*)\n"
            + "FROM ENQUIRY\n"
            + "WHERE DATE_PART('month', (CREATED_ON)) = DATE_PART('month', (NOW())) -1\n"
            + "	AND DATE_PART('year', (CREATED_ON)) = DATE_PART('year', (NOW())) AND OWNER in :owner", nativeQuery = true)
    Long lastMonthEnquiryForPartner(@Param("owner") List<Long> owner);

    Long countByStatusIn(List<String> status);

    Long countByStatusInAndOwnerIn(List<String> status, List<Long> owner);

    Long countByStatus(String status);

    Long countByStatusAndOwnerIn(String status, List<Long> owner);

}
